# Generated by Django 4.2.6 on 2023-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="descripcion",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="titulo",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(),
        ),
    ]
