# Generated by Django 4.2.6 on 2023-10-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_choice_choice_text_alter_post_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionvalue",
            name="choice",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.choice",
            ),
        ),
    ]
