# Generated by Django 4.2.6 on 2023-10-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_userquestionvalue_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquestionvalue",
            name="choice",
        ),
    ]
