# Generated by Django 4.2.6 on 2023-10-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_userquestionvalue_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionvalue",
            name="choice",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.choice",
            ),
        ),
    ]
